import RegisterForm from '@/components/LoginRegister/Register';
import { Metadata } from 'next';
import React from 'react';

export const metadata: Metadata = {
  title: "Masudur Rahman Portfolio Registration",
  description: "Generated by my portfolio registration page.",
};

const RegisterPage = () => {
    return (
        <div>
             <RegisterForm></RegisterForm>
        </div>
    );
};

export default RegisterPage;