 import { ContactForm } from '@/components/ContactForm/ContactForm';
import { Metadata } from 'next';
import React from 'react';


export const metadata: Metadata = {
  title: "Masudur Rahman Portfolio Contact",
  description: "Generated by my portfolio contact page.",
};


const ContactPage = () => {
    return (
        <div> 
            <ContactForm></ContactForm>
        </div>
    );
};

export default ContactPage;