import AllBlogs from '@/components/Blogs/AllBlogs'; 
import { Metadata } from 'next';
import React from 'react';


export const metadata: Metadata = {
  title: "Masudur Rahman Portfolio Blogs",
  description: "Generated by my portfolio blog page.",
};

const BlogsPage = () => {
    return (
        <div>
             <AllBlogs></AllBlogs>
        </div>
    );
};

export default BlogsPage;