import Blogs from '@/components/BlogsComponent/Blogs';
import { Metadata } from 'next';
import React from 'react';


export const metadata: Metadata = {
  title: "Masudur Rahman Portfolio Blogs",
  description: "Generated by my portfolio blog page.",
};

const BlogsPage = () => {
    return (
        <div>
            <Blogs></Blogs>
        </div>
    );
};

export default BlogsPage;