import Projects from '@/components/ProjectsComponent/Projects';
import { Metadata } from 'next';
import React from 'react';


export const metadata: Metadata = {
  title: "Masudur Rahman Projects",
  description: "Generated by my portfolio projects page.",
};

const ProjectsPage = () => {
    return (
        <div>
            <Projects></Projects>
        </div>
    );
};

export default ProjectsPage;