import AllProjects from '@/components/Projects/AllProjects'; 
import { Metadata } from 'next';
import React from 'react';


export const metadata: Metadata = {
  title: "Masudur Rahman Projects",
  description: "Generated by my portfolio projects page.",
};

const ProjectsPage = () => {
    return (
        <div>
             <AllProjects></AllProjects>
        </div>
    );
};

export default ProjectsPage;