import Login from '@/components/LoginRegister/Login';
import { Metadata } from 'next';
import React from 'react';


export const metadata: Metadata = {
  title: "Masudur Rahman Portfolio login",
  description: "Generated by my portfolio login page.",
};
const LoginPage = () => {
    return (
        <div>
           <Login></Login>
        </div>
    );
};

export default LoginPage;