 import GithubStats from '@/components/AboutComponent/GithubStats';
import Hobbies from '@/components/AboutComponent/Hobbies';
import { Metadata } from 'next';
import React from 'react';

export const metadata: Metadata = {
  title: "About Masudur Rahman",
  description: "Generated by my portfolio about page.",
};

const ABoutPage = () => {
    return (
        <div>
            {/* <About></About> */}
            <GithubStats></GithubStats>
            <Hobbies></Hobbies>
        </div>
    );
};

export default ABoutPage;