import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import BlurryCursor from "@/components/BlurryCursor/BlurryCursor";  
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Masudur Rahman Portfolio",
  description: "Generated by my portfolio.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <BlurryCursor></BlurryCursor>
        <Toaster></Toaster>
        <div className="min-h-screen bg-no-repeat bg-cover bg-center cover-img"
           > 
            <div className="bg-black/80">
              {children}
              </div> 
        </div>
      </body>
    </html>
  );
}
