import Banner from '@/components/HomeComponent/Banner'; 
import EducationalQualifications from '@/components/HomeComponent/EducationalQualifications'; 
import Skills from '@/components/HomeComponent/Skills';
import { Metadata } from 'next';
import React from 'react';


export const metadata: Metadata = {
  title: "Masudur Rahman Portfolio Home",
  description: "Generated by my portfolio home page.",
};

const PublicHome = () => { 
    return (
        <div>
            <Banner></Banner>  
            <Skills></Skills>
            {/* <Hobbies></Hobbies>  */}
            <EducationalQualifications></EducationalQualifications>
        </div>
    );
};

export default PublicHome;