import CreateBlogForm from '@/components/Blogs/CreateBlogsForm';
import CreateProjectForm from '@/components/Projects/CreateProjectForm';
import { Metadata } from 'next';
import React from 'react';


export const metadata: Metadata = {
  title: "Masudur Rahman Dashboard",
  description: "Generated by my portfolio dashboard page.",
};


const DashboardPage = () => {
    return (
        <div>
             <CreateProjectForm></CreateProjectForm>
             <div className='my-20'>
                <CreateBlogForm></CreateBlogForm>
             </div>
        </div>
    );
};

export default DashboardPage;